[package]
name = "shelly_websocket"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.2"
futures-util = "0.3"
tokio = { version = "1", features = ["full"] }
env_logger = "0.10"
log = "0.4"
